services:
  - type: web
    name: code-mafia-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
